/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-11-13 07:07:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/includes/top_navbar.jsp", Long.valueOf(1510548672000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("  <title>AdminLTE 2 | Dashboard</title>\n");
      out.write("  <!-- Tell the browser to be responsive to screen width -->\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\" name=\"viewport\">\n");
      out.write("  <!-- Bootstrap 3.3.7 -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"bower_components/bootstrap/dist/css/bootstrap.min.css\">\n");
      out.write("  <!-- Font Awesome -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"bower_components/font-awesome/css/font-awesome.min.css\">\n");
      out.write("  <!-- Ionicons -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"bower_components/Ionicons/css/ionicons.min.css\">\n");
      out.write("  <!-- jvectormap -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"bower_components/jvectormap/jquery-jvectormap.css\">\n");
      out.write("  <!-- Theme style -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"dist/css/AdminLTE.min.css\">\n");
      out.write("  <!-- AdminLTE Skins. Choose a skin from the css/skins\n");
      out.write("       folder instead of downloading all of them to reduce the load. -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"dist/css/skins/_all-skins.min.css\">\n");
      out.write("\n");
      out.write("  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n");
      out.write("  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("  <!--[if lt IE 9]>\n");
      out.write("  <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\n");
      out.write("  <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n");
      out.write("  <![endif]-->\n");
      out.write("\n");
      out.write("  <!-- Google Font -->\n");
      out.write("  <link rel=\"stylesheet\"\n");
      out.write("        href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic\">\n");
      out.write("</head>\n");
      out.write("<body class=\"hold-transition skin-blue sidebar-mini\">\n");
      out.write("<div class=\"wrapper\">\n");
      out.write("\n");
      out.write("<header class=\"main-header\">\n");
      out.write("    \n");
      out.write("        <!-- Logo -->\n");
      out.write("        <a href=\"index2.html\" class=\"logo\">\n");
      out.write("          <!-- mini logo for sidebar mini 50x50 pixels -->\n");
      out.write("          <span class=\"logo-mini\"><b>A</b>LT</span>\n");
      out.write("          <!-- logo for regular state and mobile devices -->\n");
      out.write("          <span class=\"logo-lg\"><b>Admin</b>LTE</span>\n");
      out.write("        </a>\n");
      out.write("    \n");
      out.write("        <!-- Header Navbar: style can be found in header.less -->\n");
      out.write("        <nav class=\"navbar navbar-static-top\">\n");
      out.write("          <!-- Sidebar toggle button-->\n");
      out.write("          <a href=\"#\" class=\"sidebar-toggle\" data-toggle=\"push-menu\" role=\"button\">\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("          </a>\n");
      out.write("          <!-- Navbar Right Menu -->\n");
      out.write("          <div class=\"navbar-custom-menu\">\n");
      out.write("            <ul class=\"nav navbar-nav\">\n");
      out.write("              <!-- Messages: style can be found in dropdown.less-->\n");
      out.write("              <li class=\"dropdown messages-menu\">\n");
      out.write("                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("                  <i class=\"fa fa-envelope-o\"></i>\n");
      out.write("                  <span class=\"label label-success\">4</span>\n");
      out.write("                </a>\n");
      out.write("                <ul class=\"dropdown-menu\">\n");
      out.write("                  <li class=\"header\">You have 4 messages</li>\n");
      out.write("                  <li>\n");
      out.write("                    <!-- inner menu: contains the actual data -->\n");
      out.write("                    <ul class=\"menu\">\n");
      out.write("                      <li><!-- start message -->\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                          <div class=\"pull-left\">\n");
      out.write("                            <img src=\"dist/img/user2-160x160.jpg\" class=\"img-circle\" alt=\"User Image\">\n");
      out.write("                          </div>\n");
      out.write("                          <h4>\n");
      out.write("                            Support Team\n");
      out.write("                            <small><i class=\"fa fa-clock-o\"></i> 5 mins</small>\n");
      out.write("                          </h4>\n");
      out.write("                          <p>Why not buy a new awesome theme?</p>\n");
      out.write("                        </a>\n");
      out.write("                      </li>\n");
      out.write("                      <!-- end message -->\n");
      out.write("                      <li>\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                          <div class=\"pull-left\">\n");
      out.write("                            <img src=\"dist/img/user3-128x128.jpg\" class=\"img-circle\" alt=\"User Image\">\n");
      out.write("                          </div>\n");
      out.write("                          <h4>\n");
      out.write("                            AdminLTE Design Team\n");
      out.write("                            <small><i class=\"fa fa-clock-o\"></i> 2 hours</small>\n");
      out.write("                          </h4>\n");
      out.write("                          <p>Why not buy a new awesome theme?</p>\n");
      out.write("                        </a>\n");
      out.write("                      </li>\n");
      out.write("                      <li>\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                          <div class=\"pull-left\">\n");
      out.write("                            <img src=\"dist/img/user4-128x128.jpg\" class=\"img-circle\" alt=\"User Image\">\n");
      out.write("                          </div>\n");
      out.write("                          <h4>\n");
      out.write("                            Developers\n");
      out.write("                            <small><i class=\"fa fa-clock-o\"></i> Today</small>\n");
      out.write("                          </h4>\n");
      out.write("                          <p>Why not buy a new awesome theme?</p>\n");
      out.write("                        </a>\n");
      out.write("                      </li>\n");
      out.write("                      <li>\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                          <div class=\"pull-left\">\n");
      out.write("                            <img src=\"dist/img/user3-128x128.jpg\" class=\"img-circle\" alt=\"User Image\">\n");
      out.write("                          </div>\n");
      out.write("                          <h4>\n");
      out.write("                            Sales Department\n");
      out.write("                            <small><i class=\"fa fa-clock-o\"></i> Yesterday</small>\n");
      out.write("                          </h4>\n");
      out.write("                          <p>Why not buy a new awesome theme?</p>\n");
      out.write("                        </a>\n");
      out.write("                      </li>\n");
      out.write("                      <li>\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                          <div class=\"pull-left\">\n");
      out.write("                            <img src=\"dist/img/user4-128x128.jpg\" class=\"img-circle\" alt=\"User Image\">\n");
      out.write("                          </div>\n");
      out.write("                          <h4>\n");
      out.write("                            Reviewers\n");
      out.write("                            <small><i class=\"fa fa-clock-o\"></i> 2 days</small>\n");
      out.write("                          </h4>\n");
      out.write("                          <p>Why not buy a new awesome theme?</p>\n");
      out.write("                        </a>\n");
      out.write("                      </li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"footer\"><a href=\"#\">See All Messages</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <!-- Notifications: style can be found in dropdown.less -->\n");
      out.write("              <li class=\"dropdown notifications-menu\">\n");
      out.write("                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("                  <i class=\"fa fa-bell-o\"></i>\n");
      out.write("                  <span class=\"label label-warning\">10</span>\n");
      out.write("                </a>\n");
      out.write("                <ul class=\"dropdown-menu\">\n");
      out.write("                  <li class=\"header\">You have 10 notifications</li>\n");
      out.write("                  <li>\n");
      out.write("                    <!-- inner menu: contains the actual data -->\n");
      out.write("                    <ul class=\"menu\">\n");
      out.write("                      <li>\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                          <i class=\"fa fa-users text-aqua\"></i> 5 new members joined today\n");
      out.write("                        </a>\n");
      out.write("                      </li>\n");
      out.write("                      <li>\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                          <i class=\"fa fa-warning text-yellow\"></i> Very long description here that may not fit into the\n");
      out.write("                          page and may cause design problems\n");
      out.write("                        </a>\n");
      out.write("                      </li>\n");
      out.write("                      <li>\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                          <i class=\"fa fa-users text-red\"></i> 5 new members joined\n");
      out.write("                        </a>\n");
      out.write("                      </li>\n");
      out.write("                      <li>\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                          <i class=\"fa fa-shopping-cart text-green\"></i> 25 sales made\n");
      out.write("                        </a>\n");
      out.write("                      </li>\n");
      out.write("                      <li>\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                          <i class=\"fa fa-user text-red\"></i> You changed your username\n");
      out.write("                        </a>\n");
      out.write("                      </li>\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"footer\"><a href=\"#\">View all</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <!-- Tasks: style can be found in dropdown.less -->\n");
      out.write("              <li class=\"dropdown tasks-menu\">\n");
      out.write("                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("                  <i class=\"fa fa-flag-o\"></i>\n");
      out.write("                  <span class=\"label label-danger\">9</span>\n");
      out.write("                </a>\n");
      out.write("                <ul class=\"dropdown-menu\">\n");
      out.write("                  <li class=\"header\">You have 9 tasks</li>\n");
      out.write("                  <li>\n");
      out.write("                    <!-- inner menu: contains the actual data -->\n");
      out.write("                    <ul class=\"menu\">\n");
      out.write("                      <li><!-- Task item -->\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                          <h3>\n");
      out.write("                            Design some buttons\n");
      out.write("                            <small class=\"pull-right\">20%</small>\n");
      out.write("                          </h3>\n");
      out.write("                          <div class=\"progress xs\">\n");
      out.write("                            <div class=\"progress-bar progress-bar-aqua\" style=\"width: 20%\" role=\"progressbar\"\n");
      out.write("                                 aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\">\n");
      out.write("                              <span class=\"sr-only\">20% Complete</span>\n");
      out.write("                            </div>\n");
      out.write("                          </div>\n");
      out.write("                        </a>\n");
      out.write("                      </li>\n");
      out.write("                      <!-- end task item -->\n");
      out.write("                      <li><!-- Task item -->\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                          <h3>\n");
      out.write("                            Create a nice theme\n");
      out.write("                            <small class=\"pull-right\">40%</small>\n");
      out.write("                          </h3>\n");
      out.write("                          <div class=\"progress xs\">\n");
      out.write("                            <div class=\"progress-bar progress-bar-green\" style=\"width: 40%\" role=\"progressbar\"\n");
      out.write("                                 aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\">\n");
      out.write("                              <span class=\"sr-only\">40% Complete</span>\n");
      out.write("                            </div>\n");
      out.write("                          </div>\n");
      out.write("                        </a>\n");
      out.write("                      </li>\n");
      out.write("                      <!-- end task item -->\n");
      out.write("                      <li><!-- Task item -->\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                          <h3>\n");
      out.write("                            Some task I need to do\n");
      out.write("                            <small class=\"pull-right\">60%</small>\n");
      out.write("                          </h3>\n");
      out.write("                          <div class=\"progress xs\">\n");
      out.write("                            <div class=\"progress-bar progress-bar-red\" style=\"width: 60%\" role=\"progressbar\"\n");
      out.write("                                 aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\">\n");
      out.write("                              <span class=\"sr-only\">60% Complete</span>\n");
      out.write("                            </div>\n");
      out.write("                          </div>\n");
      out.write("                        </a>\n");
      out.write("                      </li>\n");
      out.write("                      <!-- end task item -->\n");
      out.write("                      <li><!-- Task item -->\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                          <h3>\n");
      out.write("                            Make beautiful transitions\n");
      out.write("                            <small class=\"pull-right\">80%</small>\n");
      out.write("                          </h3>\n");
      out.write("                          <div class=\"progress xs\">\n");
      out.write("                            <div class=\"progress-bar progress-bar-yellow\" style=\"width: 80%\" role=\"progressbar\"\n");
      out.write("                                 aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\">\n");
      out.write("                              <span class=\"sr-only\">80% Complete</span>\n");
      out.write("                            </div>\n");
      out.write("                          </div>\n");
      out.write("                        </a>\n");
      out.write("                      </li>\n");
      out.write("                      <!-- end task item -->\n");
      out.write("                    </ul>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"footer\">\n");
      out.write("                    <a href=\"#\">View all tasks</a>\n");
      out.write("                  </li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <!-- User Account: style can be found in dropdown.less -->\n");
      out.write("              <li class=\"dropdown user user-menu\">\n");
      out.write("                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("                  <img src=\"dist/img/user2-160x160.jpg\" class=\"user-image\" alt=\"User Image\">\n");
      out.write("                  <span class=\"hidden-xs\">Alexander Pierce</span>\n");
      out.write("                </a>\n");
      out.write("                <ul class=\"dropdown-menu\">\n");
      out.write("                  <!-- User image -->\n");
      out.write("                  <li class=\"user-header\">\n");
      out.write("                    <img src=\"dist/img/user2-160x160.jpg\" class=\"img-circle\" alt=\"User Image\">\n");
      out.write("    \n");
      out.write("                    <p>\n");
      out.write("                      Alexander Pierce - Web Developer\n");
      out.write("                      <small>Member since Nov. 2012</small>\n");
      out.write("                    </p>\n");
      out.write("                  </li>\n");
      out.write("                  <!-- Menu Body -->\n");
      out.write("                  <li class=\"user-body\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                      <div class=\"col-xs-4 text-center\">\n");
      out.write("                        <a href=\"#\">Followers</a>\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"col-xs-4 text-center\">\n");
      out.write("                        <a href=\"#\">Sales</a>\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"col-xs-4 text-center\">\n");
      out.write("                        <a href=\"#\">Friends</a>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /.row -->\n");
      out.write("                  </li>\n");
      out.write("                  <!-- Menu Footer-->\n");
      out.write("                  <li class=\"user-footer\">\n");
      out.write("                    <div class=\"pull-left\">\n");
      out.write("                      <a href=\"#\" class=\"btn btn-default btn-flat\">Profile</a>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"pull-right\">\n");
      out.write("                      <a href=\"#\" class=\"btn btn-default btn-flat\">Sign out</a>\n");
      out.write("                    </div>\n");
      out.write("                  </li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("              <!-- Control Sidebar Toggle Button -->\n");
      out.write("              <li>\n");
      out.write("                <a href=\"#\" data-toggle=\"control-sidebar\"><i class=\"fa fa-gears\"></i></a>\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("    \n");
      out.write("        </nav>\n");
      out.write("      </header>");
      out.write("\n");
      out.write("\n");
      out.write("  <!-- Left side column. contains the logo and sidebar -->\n");
      out.write("  <aside class=\"main-sidebar\">\n");
      out.write("    <!-- sidebar: style can be found in sidebar.less -->\n");
      out.write("    <section class=\"sidebar\">\n");
      out.write("      <!-- Sidebar user panel -->\n");
      out.write("      <div class=\"user-panel\">\n");
      out.write("        <div class=\"pull-left image\">\n");
      out.write("          <img src=\"dist/img/user2-160x160.jpg\" class=\"img-circle\" alt=\"User Image\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"pull-left info\">\n");
      out.write("          <p>Alexander Pierce</p>\n");
      out.write("          <a href=\"#\"><i class=\"fa fa-circle text-success\"></i> Online</a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <!-- search form -->\n");
      out.write("      <form action=\"#\" method=\"get\" class=\"sidebar-form\">\n");
      out.write("        <div class=\"input-group\">\n");
      out.write("          <input type=\"text\" name=\"q\" class=\"form-control\" placeholder=\"Search...\">\n");
      out.write("          <span class=\"input-group-btn\">\n");
      out.write("                <button type=\"submit\" name=\"search\" id=\"search-btn\" class=\"btn btn-flat\">\n");
      out.write("                  <i class=\"fa fa-search\"></i>\n");
      out.write("                </button>\n");
      out.write("              </span>\n");
      out.write("        </div>\n");
      out.write("      </form>\n");
      out.write("      <!-- /.search form -->\n");
      out.write("      <!-- sidebar menu: : style can be found in sidebar.less -->\n");
      out.write("      <ul class=\"sidebar-menu\" data-widget=\"tree\">\n");
      out.write("        <li class=\"header\">MAIN NAVIGATION</li>\n");
      out.write("        <li class=\"active treeview menu-open\">\n");
      out.write("          <a href=\"#\">\n");
      out.write("            <i class=\"fa fa-dashboard\"></i> <span>Dashboard</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"treeview-menu\">\n");
      out.write("            <li><a href=\"index.html\"><i class=\"fa fa-circle-o\"></i> Dashboard v1</a></li>\n");
      out.write("            <li class=\"active\"><a href=\"index2.html\"><i class=\"fa fa-circle-o\"></i> Dashboard v2</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"treeview\">\n");
      out.write("          <a href=\"#\">\n");
      out.write("            <i class=\"fa fa-files-o\"></i>\n");
      out.write("            <span>Layout Options</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <span class=\"label label-primary pull-right\">4</span>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"treeview-menu\">\n");
      out.write("            <li><a href=\"pages/layout/top-nav.html\"><i class=\"fa fa-circle-o\"></i> Top Navigation</a></li>\n");
      out.write("            <li><a href=\"pages/layout/boxed.html\"><i class=\"fa fa-circle-o\"></i> Boxed</a></li>\n");
      out.write("            <li><a href=\"pages/layout/fixed.html\"><i class=\"fa fa-circle-o\"></i> Fixed</a></li>\n");
      out.write("            <li><a href=\"pages/layout/collapsed-sidebar.html\"><i class=\"fa fa-circle-o\"></i> Collapsed Sidebar</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li>\n");
      out.write("          <a href=\"pages/widgets.html\">\n");
      out.write("            <i class=\"fa fa-th\"></i> <span>Widgets</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <small class=\"label pull-right bg-green\">new</small>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"treeview\">\n");
      out.write("          <a href=\"#\">\n");
      out.write("            <i class=\"fa fa-pie-chart\"></i>\n");
      out.write("            <span>Charts</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"treeview-menu\">\n");
      out.write("            <li><a href=\"pages/charts/chartjs.html\"><i class=\"fa fa-circle-o\"></i> ChartJS</a></li>\n");
      out.write("            <li><a href=\"pages/charts/morris.html\"><i class=\"fa fa-circle-o\"></i> Morris</a></li>\n");
      out.write("            <li><a href=\"pages/charts/flot.html\"><i class=\"fa fa-circle-o\"></i> Flot</a></li>\n");
      out.write("            <li><a href=\"pages/charts/inline.html\"><i class=\"fa fa-circle-o\"></i> Inline charts</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"treeview\">\n");
      out.write("          <a href=\"#\">\n");
      out.write("            <i class=\"fa fa-laptop\"></i>\n");
      out.write("            <span>UI Elements</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"treeview-menu\">\n");
      out.write("            <li><a href=\"pages/UI/general.html\"><i class=\"fa fa-circle-o\"></i> General</a></li>\n");
      out.write("            <li><a href=\"pages/UI/icons.html\"><i class=\"fa fa-circle-o\"></i> Icons</a></li>\n");
      out.write("            <li><a href=\"pages/UI/buttons.html\"><i class=\"fa fa-circle-o\"></i> Buttons</a></li>\n");
      out.write("            <li><a href=\"pages/UI/sliders.html\"><i class=\"fa fa-circle-o\"></i> Sliders</a></li>\n");
      out.write("            <li><a href=\"pages/UI/timeline.html\"><i class=\"fa fa-circle-o\"></i> Timeline</a></li>\n");
      out.write("            <li><a href=\"pages/UI/modals.html\"><i class=\"fa fa-circle-o\"></i> Modals</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"treeview\">\n");
      out.write("          <a href=\"#\">\n");
      out.write("            <i class=\"fa fa-edit\"></i> <span>Forms</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"treeview-menu\">\n");
      out.write("            <li><a href=\"pages/forms/general.html\"><i class=\"fa fa-circle-o\"></i> General Elements</a></li>\n");
      out.write("            <li><a href=\"pages/forms/advanced.html\"><i class=\"fa fa-circle-o\"></i> Advanced Elements</a></li>\n");
      out.write("            <li><a href=\"pages/forms/editors.html\"><i class=\"fa fa-circle-o\"></i> Editors</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"treeview\">\n");
      out.write("          <a href=\"#\">\n");
      out.write("            <i class=\"fa fa-table\"></i> <span>Tables</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"treeview-menu\">\n");
      out.write("            <li><a href=\"pages/tables/simple.html\"><i class=\"fa fa-circle-o\"></i> Simple tables</a></li>\n");
      out.write("            <li><a href=\"pages/tables/data.html\"><i class=\"fa fa-circle-o\"></i> Data tables</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li>\n");
      out.write("          <a href=\"pages/calendar.html\">\n");
      out.write("            <i class=\"fa fa-calendar\"></i> <span>Calendar</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <small class=\"label pull-right bg-red\">3</small>\n");
      out.write("              <small class=\"label pull-right bg-blue\">17</small>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("        </li>\n");
      out.write("        <li>\n");
      out.write("          <a href=\"pages/mailbox/mailbox.html\">\n");
      out.write("            <i class=\"fa fa-envelope\"></i> <span>Mailbox</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <small class=\"label pull-right bg-yellow\">12</small>\n");
      out.write("              <small class=\"label pull-right bg-green\">16</small>\n");
      out.write("              <small class=\"label pull-right bg-red\">5</small>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"treeview\">\n");
      out.write("          <a href=\"#\">\n");
      out.write("            <i class=\"fa fa-folder\"></i> <span>Examples</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"treeview-menu\">\n");
      out.write("            <li><a href=\"pages/examples/invoice.html\"><i class=\"fa fa-circle-o\"></i> Invoice</a></li>\n");
      out.write("            <li><a href=\"pages/examples/profile.html\"><i class=\"fa fa-circle-o\"></i> Profile</a></li>\n");
      out.write("            <li><a href=\"pages/examples/login.html\"><i class=\"fa fa-circle-o\"></i> Login</a></li>\n");
      out.write("            <li><a href=\"pages/examples/register.html\"><i class=\"fa fa-circle-o\"></i> Register</a></li>\n");
      out.write("            <li><a href=\"pages/examples/lockscreen.html\"><i class=\"fa fa-circle-o\"></i> Lockscreen</a></li>\n");
      out.write("            <li><a href=\"pages/examples/404.html\"><i class=\"fa fa-circle-o\"></i> 404 Error</a></li>\n");
      out.write("            <li><a href=\"pages/examples/500.html\"><i class=\"fa fa-circle-o\"></i> 500 Error</a></li>\n");
      out.write("            <li><a href=\"pages/examples/blank.html\"><i class=\"fa fa-circle-o\"></i> Blank Page</a></li>\n");
      out.write("            <li><a href=\"pages/examples/pace.html\"><i class=\"fa fa-circle-o\"></i> Pace Page</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"treeview\">\n");
      out.write("          <a href=\"#\">\n");
      out.write("            <i class=\"fa fa-share\"></i> <span>Multilevel</span>\n");
      out.write("            <span class=\"pull-right-container\">\n");
      out.write("              <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("            </span>\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"treeview-menu\">\n");
      out.write("            <li><a href=\"#\"><i class=\"fa fa-circle-o\"></i> Level One</a></li>\n");
      out.write("            <li class=\"treeview\">\n");
      out.write("              <a href=\"#\"><i class=\"fa fa-circle-o\"></i> Level One\n");
      out.write("                <span class=\"pull-right-container\">\n");
      out.write("                  <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("                </span>\n");
      out.write("              </a>\n");
      out.write("              <ul class=\"treeview-menu\">\n");
      out.write("                <li><a href=\"#\"><i class=\"fa fa-circle-o\"></i> Level Two</a></li>\n");
      out.write("                <li class=\"treeview\">\n");
      out.write("                  <a href=\"#\"><i class=\"fa fa-circle-o\"></i> Level Two\n");
      out.write("                    <span class=\"pull-right-container\">\n");
      out.write("                      <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("                    </span>\n");
      out.write("                  </a>\n");
      out.write("                  <ul class=\"treeview-menu\">\n");
      out.write("                    <li><a href=\"#\"><i class=\"fa fa-circle-o\"></i> Level Three</a></li>\n");
      out.write("                    <li><a href=\"#\"><i class=\"fa fa-circle-o\"></i> Level Three</a></li>\n");
      out.write("                  </ul>\n");
      out.write("                </li>\n");
      out.write("              </ul>\n");
      out.write("            </li>\n");
      out.write("            <li><a href=\"#\"><i class=\"fa fa-circle-o\"></i> Level One</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li><a href=\"https://adminlte.io/docs\"><i class=\"fa fa-book\"></i> <span>Documentation</span></a></li>\n");
      out.write("        <li class=\"header\">LABELS</li>\n");
      out.write("        <li><a href=\"#\"><i class=\"fa fa-circle-o text-red\"></i> <span>Important</span></a></li>\n");
      out.write("        <li><a href=\"#\"><i class=\"fa fa-circle-o text-yellow\"></i> <span>Warning</span></a></li>\n");
      out.write("        <li><a href=\"#\"><i class=\"fa fa-circle-o text-aqua\"></i> <span>Information</span></a></li>\n");
      out.write("      </ul>\n");
      out.write("    </section>\n");
      out.write("    <!-- /.sidebar -->\n");
      out.write("  </aside>\n");
      out.write("\n");
      out.write("  <!-- Content Wrapper. Contains page content -->\n");
      out.write("  <div class=\"content-wrapper\">\n");
      out.write("    <!-- Content Header (Page header) -->\n");
      out.write("    <section class=\"content-header\">\n");
      out.write("      <h1>\n");
      out.write("        Dashboard\n");
      out.write("        <small>Version 2.0</small>\n");
      out.write("      </h1>\n");
      out.write("      <ol class=\"breadcrumb\">\n");
      out.write("        <li><a href=\"#\"><i class=\"fa fa-dashboard\"></i> Home</a></li>\n");
      out.write("        <li class=\"active\">Dashboard</li>\n");
      out.write("      </ol>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    \n");
      out.write("</div>\n");
      out.write("<!-- ./wrapper -->\n");
      out.write("\n");
      out.write("<!-- jQuery 3 -->\n");
      out.write("<script src=\"bower_components/jquery/dist/jquery.min.js\"></script>\n");
      out.write("<!-- Bootstrap 3.3.7 -->\n");
      out.write("<script src=\"bower_components/bootstrap/dist/js/bootstrap.min.js\"></script>\n");
      out.write("<!-- FastClick -->\n");
      out.write("<script src=\"bower_components/fastclick/lib/fastclick.js\"></script>\n");
      out.write("<!-- AdminLTE App -->\n");
      out.write("<script src=\"dist/js/adminlte.min.js\"></script>\n");
      out.write("<!-- Sparkline -->\n");
      out.write("<script src=\"bower_components/jquery-sparkline/dist/jquery.sparkline.min.js\"></script>\n");
      out.write("<!-- jvectormap  -->\n");
      out.write("<script src=\"plugins/jvectormap/jquery-jvectormap-1.2.2.min.js\"></script>\n");
      out.write("<script src=\"plugins/jvectormap/jquery-jvectormap-world-mill-en.js\"></script>\n");
      out.write("<!-- SlimScroll -->\n");
      out.write("<script src=\"bower_components/jquery-slimscroll/jquery.slimscroll.min.js\"></script>\n");
      out.write("<!-- ChartJS -->\n");
      out.write("<script src=\"bower_components/Chart.js/Chart.js\"></script>\n");
      out.write("<!-- AdminLTE dashboard demo (This is only for demo purposes) -->\n");
      out.write("<script src=\"dist/js/pages/dashboard2.js\"></script>\n");
      out.write("<!-- AdminLTE for demo purposes -->\n");
      out.write("<script src=\"dist/js/demo.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
